name: cotton-candy

services:
  cotton-candy:
    container_name: cotton-candy
    expose:
      - 3000
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    restart: on-failure

  backend:
    container_name: cotton-candy-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: on-failure
